In [1]:
import pandas as pd
import glob
import os
from IPython.core.display import display, HTML

In [41]:
input_file = r'/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2'
output_file = r'/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2/travel_final_2.csv'

In [42]:
allFile_list =[]
for i in range(109):
    allFile_list.append(glob.glob(os.path.join(input_file, 'travel_example{}.csv'.format(i))))

In [43]:
allFile_list = sum(allFile_list, [])

In [44]:
allData = []
for file in allFile_list:
    print(file)
    df = pd.read_csv(file, header=None)
    allData.append(df)

/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example0.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example1.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example2.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example3.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example4.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example5.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example6.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example7.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example8.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example9.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example10.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example11.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example12.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example13.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example14.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example15.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example16.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example17.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example18.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example19.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example20.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example21.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example22.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example23.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example24.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example25.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example26.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example27.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example28.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example29.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example30.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example31.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example32.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example33.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example34.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example35.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example36.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example37.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example38.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example39.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example40.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example41.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example42.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example43.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example44.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example45.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example46.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example47.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example48.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example49.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example50.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example51.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example52.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example53.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example54.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example55.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example56.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example57.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example58.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example59.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example60.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example61.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example62.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example63.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example64.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example65.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example66.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example67.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example68.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example69.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example70.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example71.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example72.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example73.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example74.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example75.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example76.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example77.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example78.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example79.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example80.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example81.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example82.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example83.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example84.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example85.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example86.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example87.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example88.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example89.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example90.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example91.csv

/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example92.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example93.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example94.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example95.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example96.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example97.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example98.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example99.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example100.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example101.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example102.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example103.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example104.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example105.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example106.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example107.csv
/Users/shine/Documents/Project//Broomies//03_Watson/DATA/watson_travel_data2\travel_example108.csv

In [45]:
allData

[             0                  1  \
 0  {"code":400  sub_code:"S00015"

                                                    2  \
 0  error:"The input you provided matched 57 words...

                                                    3
 0   we require 70 matching words to calculate cha...  ,
         0         1         2        3         4         5         6    \
 0  0.274559  0.162584  0.981835  0.01242  0.920962  0.097895  0.839866

        7        8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.98661  0.96855  0.866063  ...  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  0.5

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.850785  0.620365  0.999474  0.005551  0.997818  0.883538  0.958251

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.994898  0.996189  0.984124  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1        2         3         4         5         6    \
 0  0.720432  0.427747  0.99583  0.032247  0.882489  0.338484  0.557568

         7        8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.923607  0.96955  0.858502  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  0.5

 [1 rows x 231 columns],
         0         1         2         3         4         5        6    \
 0  0.772117  0.349532  0.991826  0.004685  0.932716  0.540819  0.88102

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.978909  0.973225  0.932049  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1        2         3         4         5         6    \
 0  0.773191  0.443507  0.99456  0.022322  0.929336  0.440674  0.531265

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.947377  0.990579  0.990722  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1         2        3         4         5         6    \
 0  0.634672  0.140077  0.999818  0.00804  0.989139  0.111755  0.649479

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.997075  0.998156  0.992935  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1        2         3         4         5         6    \
 0  0.734633  0.532925  0.97988  0.000471  0.824129  0.856752  0.927336

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.993911  0.997287  0.949238  ...  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.932736  0.644123  0.986188  0.005855  0.972679  0.865838  0.995905

         7        8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.984714  0.99213  0.868139  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
              0                  1  \
 0  {"code":400  sub_code:"S00015"

                                                    2  \
 0  error:"The input you provided matched 67 words...

                                                    3
 0   we require 70 matching words to calculate cha...  ,
         0         1         2         3         4         5         6    \
 0  0.739058  0.586083  0.977757  0.037236  0.893262  0.481748  0.936462

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.965743  0.983661  0.740139  ...  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0

    229  230
 0  0.5  0.5

 [1 rows x 231 columns],
         0         1         2         3         4       5         6    \
 0  0.873862  0.819581  0.984683  0.006506  0.821014  0.7045  0.975389

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.971582  0.987424  0.727625  ...  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1        2         3         4         5         6    \
 0  0.173016  0.161699  0.97437  0.001658  0.868355  0.049802  0.974123

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.996205  0.960397  0.728686  ...  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0

    229  230
 0  0.5  0.5

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.896588  0.903841  0.983231  0.008529  0.891719  0.932971  0.978787

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.997038  0.999246  0.906645  ...  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
              0                  1  \
 0  {"code":400  sub_code:"S00015"

                                                    2  \
 0  error:"The input you provided matched 60 words...

                                                    3
 0   we require 70 matching words to calculate cha...  ,
              0                  1  \
 0  {"code":400  sub_code:"S00015"

                                                    2  \
 0  error:"The input you provided matched 67 words...

                                                    3
 0   we require 70 matching words to calculate cha...  ,
              0                  1  \
 0  {"code":400  sub_code:"S00015"

                                                    2  \
 0  error:"The input you provided matched 45 words...

                                                    3
 0   we require 70 matching words to calculate cha...  ,
         0         1         2         3         4         5         6    \
 0  0.708072  0.459413  0.989425  0.009205  0.949554  0.858531  0.681647

         7        8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.996594  0.99578  0.872056  ...  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.216877  0.120358  0.907525  0.000622  0.829687  0.598658  0.931739

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.663184  0.645233  0.496118  ...  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.040192  0.045372  0.686951  0.000655  0.573488  0.265728  0.627025

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.864846  0.652431  0.535861  ...  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
        0         1         2         3         4         5         6    \
 0  0.79433  0.614763  0.985812  0.016881  0.976224  0.751635  0.983033

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.958469  0.985357  0.867693  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1         2         3         4        5         6    \
 0  0.127505  0.104976  0.780605  0.000626  0.812113  0.22499  0.913581

         7         8        9    ...  221  222  223  224  225  226  227  228  \
 0  0.962338  0.881948  0.76565  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.211064  0.112785  0.974741  0.001785  0.975738  0.334743  0.714385

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.880698  0.832389  0.943312  ...  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.808912  0.423727  0.976341  0.000165  0.989724  0.800491  0.958724

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.983017  0.972145  0.811164  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.311415  0.129495  0.989958  0.003604  0.931613  0.068102  0.990952

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.986783  0.975412  0.948949  ...  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1         2        3         4         5         6    \
 0  0.311463  0.087876  0.837094  0.00014  0.975849  0.468143  0.947176

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.950935  0.681787  0.445564  ...  1.0  1.0  1.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  0.5

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.871681  0.479752  0.989328  0.000291  0.934895  0.930246  0.961798

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.990932  0.977935  0.753142  ...  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.929381  0.519972  0.935976  0.000435  0.943739  0.756519  0.999325

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.978743  0.943337  0.876418  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
              0                  1  \
 0  {"code":400  sub_code:"S00015"

                                                    2  \
 0  error:"The input you provided matched 54 words...

                                                    3
 0   we require 70 matching words to calculate cha...  ,
         0         1         2         3         4         5         6    \
 0  0.486108  0.597861  0.922969  0.000122  0.786577  0.828793  0.995832

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.948148  0.845084  0.535059  ...  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.154174  0.226556  0.927938  0.007237  0.734011  0.109285  0.884213

         7       8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.964649  0.8342  0.509717  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.080872  0.432472  0.995868  0.005805  0.949386  0.225954  0.947983

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.945793  0.957982  0.605454  ...  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0

    229  230
 0  0.5  0.5

 [1 rows x 231 columns],
         0         1         2        3         4        5         6    \
 0  0.313236  0.195012  0.980248  0.00399  0.887441  0.34303  0.951738

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.934297  0.869657  0.674285  ...  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
        0         1         2         3         4         5         6    \
 0  0.52516  0.231847  0.971065  0.027969  0.998325  0.786171  0.643075

        7       8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.99606  0.9883  0.949043  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.637207  0.680475  0.845479  0.000606  0.918759  0.792742  0.999725

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.989074  0.920315  0.452209  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
        0         1         2       3         4         5         6    \
 0  0.37796  0.047486  0.921251  0.0065  0.922199  0.621047  0.939241

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.852327  0.713838  0.587538  ...  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
              0                  1  \
 0  {"code":400  sub_code:"S00015"

                                                    2  \
 0  error:"The input you provided matched 59 words...

                                                    3
 0   we require 70 matching words to calculate cha...  ,
              0                  1  \
 0  {"code":400  sub_code:"S00015"

                                                    2  \
 0  error:"The input you provided matched 60 words...

                                                    3
 0   we require 70 matching words to calculate cha...  ,
         0         1         2         3         4         5         6    \
 0  0.653578  0.474844  0.973241  0.014452  0.911047  0.470543  0.756429

         7        8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.916472  0.91081  0.634857  ...  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
              0                  1  \
 0  {"code":400  sub_code:"S00015"

                                                    2  \
 0  error:"The input you provided matched 47 words...

                                                    3
 0   we require 70 matching words to calculate cha...  ,
              0                  1  \
 0  {"code":400  sub_code:"S00015"

                                                    2  \
 0  error:"The input you provided matched 62 words...

                                                    3
 0   we require 70 matching words to calculate cha...  ,
              0                  1  \
 0  {"code":400  sub_code:"S00015"

                                                    2  \
 0  error:"The input you provided matched 50 words...

                                                    3
 0   we require 70 matching words to calculate cha...  ,
              0                  1  \
 0  {"code":400  sub_code:"S00015"

                                                    2  \
 0  error:"The input you provided matched 39 words...

                                                    3
 0   we require 70 matching words to calculate cha...  ,
         0         1       2         3         4         5         6    \
 0  0.261633  0.095842  0.8237  0.000023  0.755375  0.216542  0.823659

         7      8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.968031  0.918  0.709165  ...  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.668551  0.509992  0.967833  0.010092  0.938158  0.660504  0.992752

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.989017  0.977632  0.644082  ...  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0

    229  230
 0  0.0  1.0

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.865505  0.462168  0.979581  0.237898  0.982437  0.598034  0.734779

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.950674  0.969857  0.694346  ...  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0

    229  230
 0  0.5  0.5

 [1 rows x 231 columns],
              0                  1  \
 0  {"code":400  sub_code:"S00015"

                                                    2  \
 0  error:"The input you provided matched 56 words...

                                                    3
 0   we require 70 matching words to calculate cha...  ,
              0                  1  \
 0  {"code":400  sub_code:"S00014"

                                                    2
 0  error:"The number of words 81 is less than the...  ,
              0                  1  \
 0  {"code":400  sub_code:"S00015"

                                                    2  \
 0  error:"The input you provided matched 51 words...

                                                    3
 0   we require 70 matching words to calculate cha...  ,
       0         1         2         3         4         5         6    \
 0  0.9415  0.732741  0.972253  0.009013  0.990156  0.992696  0.999552

        7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.97484  0.920932  0.620144  ...  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  0.5

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.914302  0.742781  0.996153  0.016601  0.980539  0.605074  0.973027

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.980003  0.984348  0.703301  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  0.5

 [1 rows x 231 columns],
        0         1        2         3         4         5         6    \
 0  0.44436  0.375392  0.95266  0.010401  0.835731  0.244844  0.929686

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.983678  0.968307  0.582901  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.816141  0.484699  0.998353  0.003703  0.939889  0.490541  0.876366

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.998642  0.998894  0.926253  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  0.5

 [1 rows x 231 columns],
         0         1         2         3         4         5         6    \
 0  0.249163  0.364152  0.992325  0.000145  0.911939  0.126505  0.946418

         7        8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.998602  0.99714  0.900023  ...  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
              0                  1  \
 0  {"code":400  sub_code:"S00015"

                                                    2  \
 0  error:"The input you provided matched 61 words...

                                                    3
 0   we require 70 matching words to calculate cha...  ,
         0         1         2         3         4         5         6    \
 0  0.977221  0.805336  0.997889  0.036966  0.956931  0.749535  0.155995

         7         8        9    ...  221  222  223  224  225  226  227  228  \
 0  0.993468  0.999784  0.99971  ...  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0

    229  230
 0  0.0  1.0

 [1 rows x 231 columns],
        0         1         2         3         4        5         6    \
 0  0.72998  0.453327  0.989329  0.007751  0.819817  0.12879  0.773109

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.951601  0.931703  0.742898  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0

    229  230
 0  0.5  1.0

 [1 rows x 231 columns],
              0                  1  \
 0  {"code":400  sub_code:"S00015"

                                                    2  \
 0  error:"The input you provided matched 57 words...

                                                    3
 0   we require 70 matching words to calculate cha...  ,
         0         1         2         3         4         5         6    \
 0  0.209131  0.333597  0.998275  0.000005  0.922969  0.840384  0.986923

         7         8         9    ...  221  222  223  224  225  226  227  228  \
 0  0.984151  0.996634  0.988273  ...  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0

In [46]:
dataCombine = pd.concat(allData, axis=0, ignore_index=False)

In [47]:
dataCombine

,0,1,2,3,4,5,6,7,8,9,...,221,222,223,224,225,226,227,228,229,230
0,"{""code"":400","sub_code:""S00015""","error:""The input you provided matched 57 words...",we require 70 matching words to calculate cha...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,0.274559,0.162584,0.981835,0.0124196,0.920962,0.097895,0.839866,0.986610,0.968550,0.866063,...,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,0.5
0,0.850785,0.620365,0.999474,0.00555143,0.997818,0.883538,0.958251,0.994898,0.996189,0.984124,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0
0,0.720432,0.427747,0.99583,0.0322465,0.882489,0.338484,0.557568,0.923607,0.969550,0.858502,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,0.5
0,0.772117,0.349532,0.991826,0.00468457,0.932716,0.540819,0.881020,0.978909,0.973225,0.932049,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,0.354422,0.556862,0.90615,0.0127911,0.820390,0.671716,0.983080,0.943895,0.887099,0.594494,...,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0
0,0.553953,0.258015,0.966833,0.0120505,0.966645,0.468490,0.976218,0.964273,0.786755,0.710829,...,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,0.5
0,0.282405,0.34224,0.994526,0.0381621,0.845747,0.064051,0.619875,0.982501,0.979336,0.336808,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.5,0.5
0,0.798762,0.203771,0.996903,0.0196975,0.998629,0.105157,0.830615,0.928611,0.912735,0.875356,...,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,0.5
0,0.278741,0.112279,0.829787,0.000185704,0.917968,0.801220,0.939145,0.988205,0.901914,0.568076,...,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0

In [52]:
temp = pd.read_csv('../03_Watson/DATA/travel_labeling_2.csv', index_col=0).reset_index()
temp = temp[:109]

In [53]:
temp

,code,country,city_name,guide_type,title,intro,review,area,interest,company
0,36982,Turkey,Cappadocia,가이드 투어,[투어] 카파도키아 투어 필수 그린투어(한국어/영어) :: 터키/카파도키아,카파도키아에서 특별한 장소를 가고 싶다면 꼭 필요한 투어 그린투어 입니다차량으로 대...,정말 좋았습니다^^가이드분이 한국어 너무잘하시고 재밌어요!무스타파 가이드님 쵝오!!...,자연,Kn,혼자
1,47103,Turkey,Cappadocia,가이드 투어,[투어] 한국어/영어 카파도키아 그린투어 :: 터키/카파도키아,**3월은 코로나바이러스 입국제한 등으로 인하여 한국어투어를 위한 모객이 부족한 ...,"가이드님도 좋았고, 여행 코스 자체가 알찼습니다~한국어 가이드가 모객 부족으로 영어...",자연,Kn,가족
2,45262,Portugal,lisbon,가이드 투어,리스본 미식워킹투어 (포르투갈/리스본),'포르투는 일하고 코임브라는 공부하고 브라가는 기도하고 리스본에서 즐긴다.' 라는 ...,"어머니랑 둘이 떠나는 여행이었는데, 너무너무 좋았어요! 설명도 친절하고 자세하게 잘...",도시,Fo,혼자
3,32452,Portugal,lisbon,가이드 투어,[한국어 투어]'로맨틱 파라다이스' 신트라(포르투갈/리스본),리스본에서 30분만 벗어나도 전혀 다른 세상이 펼쳐집니다. 시인 바이런이 '에덴 동...,리스본 오신다면 신트라를 빼먹을수없죠 설명은 물론이고 정말 친절하시고 재밌습니다 여...,자연,Sh,혼자
4,48672,Portugal,Porto,가이드 투어,[투어]나만 알고 싶은 포르투 낭만투어 [낮워킹투어+야경포함] [예약시 리스본 또...,*3월 투어부터는 기존 출발시간인 오후 2시 출발로 변경됩니다. 식사시간은 오후 6...,가이드님이 너무 너무 너무 친절하시고 설명도 쉽게 잘 해주셨어요! 포르토가 언덕이 ...,도시,Ex,혼자
...,...,...,...,...,...,...,...,...,...,...
104,38924,Myanmar,Yangon,가이드 투어,양곤 근교 : 바고 프라이빗 일일 투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처를 지참하셔야...",양곤 여행시 꼭 가볼만한 코스이고가이드 또한 좋았습니다~,도시,Kn,허니문
105,20794,Myanmar,Yangon,가이드 투어,양곤에서 떠나는 바고(Bago) 문화 개별투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처를 지참하셔...",미얀마 시골을 볼수있는 좋은 찬스,자연,Kn,친구
106,27903,Viet Nam,Da Nang,가이드 투어,[투어] 다낭 바나힐 체크아웃 단독투어+11시간 내맘대로 차량이용+공항드랍:: 베트...,[투어안내]모르는 사람들과 같이 다니고 가이드 눈치보는거 싫은신 분들은 꼭 선택하세...,피곤하지않았던게 가장컸습니다.운전을 너무 잘해주셔서 편안하게 다녔어요~ 어디로 픽업...,자연,Ex,친구
107,37561,Viet Nam,Halong Bay,가이드 투어,[투어] [하노이] 하롱베이당일 티톱섬방문투어(하롱베이-하노이 왕복 고속도로이용),하롱베이는 하노이에서는 약 170km거리이고 차량으로는 4시간 정도 소요된다. 19...,현지가이드가 챙겨주는 느낌은 없었지만그래도 즐거운 투어였어요가이드가 잘생겼어요. 너...,자연,Ex,친구
108,64815,Brunei,Bandar Seri Begawan,가이드 투어,[투어] 브루나이 시티 투어 + 수상마을 캄퐁 아에르 투어 (브루나이/반다르스리브가완),*최소 모객 인원은 2인입니다. 투어 7일 전까지 2인이 모객되지 않을 경우 투어가...,"가이드님이 너무 상세하게 브루나이, 역사에 대해 설명해주셔서 3시간이 금방 갔네요....",도시,Ex,가족

In [54]:
list(temp['title'])
list(temp['code'])

[36982,
 47103,
 45262,
 32452,
 48672,
 36308,
 33556,
 53192,
 14231,
 58965,
 55623,
 52325,
 46801,
 55609,
 8490,
 1476,
 1297,
 37726,
 16081,
 9696,
 42480,
 34407,
 42575,
 16495,
 24616,
 57624,
 14538,
 14458,
 29239,
 39841,
 10360,
 39840,
 18893,
 29266,
 44044,
 44045,
 45707,
 17333,
 27491,
 29235,
 55171,
 58826,
 52022,
 34727,
 38135,
 34759,
 54195,
 52198,
 38145,
 61789,
 72633,
 8686,
 8682,
 9910,
 8394,
 4752,
 10188,
 42485,
 35058,
 10171,
 26810,
 26811,
 24932,
 22204,
 18588,
 24314,
 18700,
 35176,
 27032,
 25822,
 48669,
 5675,
 18098,
 33611,
 56472,
 14977,
 36900,
 26969,
 26964,
 47351,
 26966,
 47344,
 65335,
 49425,
 55064,
 50903,
 45935,
 24588,
 24609,
 46415,
 43233,
 43230,
 12103,
 18232,
 33455,
 48955,
 41521,
 65360,
 31243,
 44560,
 33008,
 59560,
 39490,
 39485,
 38924,
 20794,
 27903,
 37561,
 64815]

In [55]:
dataCombine['title'] = np.nan
dataCombine['code'] = np.nan
dataCombine['code'] = list(temp['code'])
dataCombine['title'] = list(temp['title'])
dataCombine

,0,1,2,3,4,5,6,7,8,9,...,223,224,225,226,227,228,229,230,title,code
0,"{""code"":400","sub_code:""S00015""","error:""The input you provided matched 57 words...",we require 70 matching words to calculate cha...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[투어] 카파도키아 투어 필수 그린투어(한국어/영어) :: 터키/카파도키아,36982
0,0.274559,0.162584,0.981835,0.0124196,0.920962,0.097895,0.839866,0.986610,0.968550,0.866063,...,0.0,0.0,1.0,1.0,0.0,1.0,0.5,0.5,[투어] 한국어/영어 카파도키아 그린투어 :: 터키/카파도키아,47103
0,0.850785,0.620365,0.999474,0.00555143,0.997818,0.883538,0.958251,0.994898,0.996189,0.984124,...,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,리스본 미식워킹투어 (포르투갈/리스본),45262
0,0.720432,0.427747,0.99583,0.0322465,0.882489,0.338484,0.557568,0.923607,0.969550,0.858502,...,0.0,0.0,1.0,1.0,0.0,1.0,0.5,0.5,[한국어 투어]'로맨틱 파라다이스' 신트라(포르투갈/리스본),32452
0,0.772117,0.349532,0.991826,0.00468457,0.932716,0.540819,0.881020,0.978909,0.973225,0.932049,...,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,[투어]나만 알고 싶은 포르투 낭만투어 [낮워킹투어+야경포함] [예약시 리스본 또...,48672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,0.354422,0.556862,0.90615,0.0127911,0.820390,0.671716,0.983080,0.943895,0.887099,0.594494,...,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,양곤 근교 : 바고 프라이빗 일일 투어,38924
0,0.553953,0.258015,0.966833,0.0120505,0.966645,0.468490,0.976218,0.964273,0.786755,0.710829,...,0.0,0.0,1.0,1.0,0.0,1.0,0.5,0.5,양곤에서 떠나는 바고(Bago) 문화 개별투어,20794
0,0.282405,0.34224,0.994526,0.0381621,0.845747,0.064051,0.619875,0.982501,0.979336,0.336808,...,0.0,0.0,0.0,1.0,0.0,0.0,0.5,0.5,[투어] 다낭 바나힐 체크아웃 단독투어+11시간 내맘대로 차량이용+공항드랍:: 베트...,27903
0,0.798762,0.203771,0.996903,0.0196975,0.998629,0.105157,0.830615,0.928611,0.912735,0.875356,...,0.0,0.0,1.0,1.0,0.0,1.0,0.5,0.5,[투어] [하노이] 하롱베이당일 티톱섬방문투어(하롱베이-하노이 왕복 고속도로이용),37561
0,0.278741,0.112279,0.829787,0.000185704,0.917968,0.801220,0.939145,0.988205,0.901914,0.568076,...,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,[투어] 브루나이 시티 투어 + 수상마을 캄퐁 아에르 투어 (브루나이/반다르스리브가완),64815

In [58]:
dataCombine.to_csv(output_file, index=False)

In [59]:
result = pd.read_csv('../03_Watson/DATA/watson_travel_data/travel_final_1.csv')
result2 = pd.read_csv('../03_Watson/DATA/watson_travel_data2/travel_final_2.csv')

In [63]:
df_result_concat = pd.concat([result, result2])

In [67]:
df_result_concat2 = df_result_concat.reset_index()

In [68]:
df_result_concat2.to_csv("../03_Watson/DATA/watson_travel_final_209.csv", index=False)