### Labeling
- area(by their destination) :

    - 도시(City) : 야경, 관광, 쇼핑(seeing nightlight, walking local street, interesting fashion)
    - 자연(Nature) : 바다, 산, 별빛(seeing stars, the seaside, plant-holic, animal-holic)

- company(by their traveling purpose) :

    - 가족: parents, children,
    - 친구: friends
    - 혼자: alone, official, etc
    - 허니문: honeymoon, partner, lover

- interest :

    - 지식추구(Kn, Knowledge) : 역사, 궁, 사원, 건축물(history, science)
    - 문화예술(Ar, Culture&Art) : 박물관, 미술관(music, museum, art museum)
    - 도전(Ad, Adventure) : 캠핑, 하이킹, 스노클링(hiking, extreme sports, snorkeling)
    - 체험(Ex, Experience) : 농장투어, 만들기 체험, 크루즈체험, 돌고래(writing, making stuffs)
    - 보여주기(Sh, like to showing) : 셀피, 스냅사진(selfie, sanp picture, like to express themselves)
    - 음식(Fo, Food-lovers) : 식문화, 맛집, 와인투어(cooking, local food, Michelin et Cie, wine tour)
    - 오락(Et, Entertainment) : 카지노

### 데이터로드 - activity

In [1]:
activity = pd.read_csv("../DATA/labeled_travel_data_363.csv", index_col=0).reset_index(drop=True)

In [153]:
activity

,code,country,city_name,score,selling_count,reviews_count,guide_type,title,intro,review,travel_purpose,purpose,age_group,drop,area,company,interest,label
0,2122,Netherlands,Amsterdam,4.73,231,84,가이드 투어,국립박물관과 고흐 미술관 대표작 설명,국립박물관은 렘브란트(Rermbrandt)의 대표작 '야경꾼'을 전시하기 위한 목적...,좋긴 좋았습니다. 가이드님이 없었으면 중요 작품들이 무엇인지 알지 못했으니까요. 하...,"{'purpose': 'etc', 'age_group': '30'}",etc,30,N,도시,혼자,Ar,2
1,1474,Netherlands,Amsterdam,4.61,160,49,가이드 투어,암스테르담 시내 워킹투어,암스테르담은 네덜란드의 수도로서 운치와 분위기가 있는 도시입니다.그럼에도 불구하고 ...,두명이서 다녔는데 시간을 알차게 계획하시구 또 전문성있게 잘 설명해주셔서 재밌었습니...,"{'purpose': 'official', 'age_group': '30'}",official,30,N,도시,혼자,Ex,2
2,34700,Netherlands,Amsterdam,4.95,104,43,가이드 투어,네덜란드 암스테르담 시내 실속 워킹투어,암스테르담을 실속있게 둘러볼 수 있는 투어입니다. 레이오버로 암스테르담에 잠깐 들...,암스테르담에 오시면 꼭꼭 들어보기를 추천드려요! 머무르는 기간이 짧든 길든 특히 첫...,"{'purpose': 'honeymoon', 'age_group': '30'}",honeymoon,30,N,도시,허니문,Ar,2
3,460,Netherlands,Volendam,4.83,154,41,가이드 투어,"히트호른, 폴른담, 풍차마을",작은 베네치아라는 별명을 가진 히트호른 마을과 네덜란드에서 가장 아름다운 전통의상을...,장거리 운전이라 힘드셨을텐데도 친절하게 잘 안내해주시고 설명도 잘 해주셨습니다 감사...,"{'purpose': 'friends', 'age_group': '30'}",friends,30,N,자연,친구,Ex,2
4,8693,Czech Republic,Praha,4.56,2353,802,가이드 투어,"[1+1이벤트/가격할인]프라하근교차량투어""독일 드레스덴&작센의스위스""(#할인쿠폰제공#)",*안녕하세요 하이프라하입니다! 이벤트 공지사항 1+1이벤트 공지입니다.독일 드...,일단 원래 후기를 잘 적지 않는데이번은 꼭 적어야 할 것 같아요너무 만족스러운 투어...,"{'purpose': 'alone', 'age_group': '30'}",alone,30,N,자연,혼자,Ex,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,59787,Cambodia,Siem Reap,4.67,13,6,가이드 투어,시엠립 : 톤레삽 호수 & 깜퐁 플럭 수상 마을 투어,"본 투어는 영어로 진행되며, 다국적 여행자들과 함께하는 단체 투어로 진행됩니다. ...",잘 다녀왓습니다~ 이국적인 풍경을 볼수 있어서 좋았네요ㅋ건기 때 가서 수상가옥은 못...,"{'purpose': 'children', 'age_group': '40'}",children,40,N,자연,가족,Ex,2
359,38589,Cambodia,Siem Reap,4.67,13,6,가이드 투어,씨엠립 : 앙코르와트 소규모 그룹 일일투어,"본 투어는 영어로 진행되며, 다국적 여행자들과 함께하는 단체 투어로 진행됩니다. ...",very good for short trip plan더웠지만 그래도 당연히 해야하는...,"{'purpose': 'partner', 'age_group': '30'}",partner,30,N,자연,가족,Ex,2
360,38589,Cambodia,Siem Reap,4.67,13,6,가이드 투어,씨엠립 : 앙코르와트 소규모 그룹 일일투어,"본 투어는 영어로 진행되며, 다국적 여행자들과 함께하는 단체 투어로 진행됩니다. ...",very good for short trip plan더웠지만 그래도 당연히 해야하는...,"{'purpose': 'partner', 'age_group': '30'}",partner,30,N,자연,가족,Ex,2
361,22031,Thailand,Bangkok,4.51,1932,483,가이드 투어,[마리트x몽키트래블] 아유타야 선셋 투어,[투어 핵심 포인트] 1. 세계문화유산으로 등재 되어있는 태국 고대도시 아유타야를 ...,한국어를 능숙하게 하시는 현지 가이드 분들이 진행하는 투어 포인트에서 이쁜 추억을 ...,"{'purpose': 'lover', 'age_group': '20'}",lover,20,N,자연,허니문,Ex,2
362,22031,Thailand,Bangkok,4.51,1932,483,가이드 투어,[마리트x몽키트래블] 아유타야 선셋 투어,[투어 핵심 포인트] 1. 세계문화유산으로 등재 되어있는 태국 고대도시 아유타야를 ...,한국어를 능숙하게 하시는 현지 가이드 분들이 진행하는 투어 포인트에서 이쁜 추억을 ...,"{'purpose': 'lover', 'age_group': '20'}",lover,20,N,자연,허니문,Ex,2

In [183]:
activity[activity['country'] == 'Myanmar']

,code,country,city_name,score,selling_count,reviews_count,guide_type,title,intro,review,travel_purpose,purpose,age_group,drop,area,company,interest,label
316,59560,Myanmar,Yangon,5.0,3,1,가이드 투어,양곤 : 어촌마을 달라(Dala)로의 반나절 관광 투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처를 지참하셔...",편하게 잘 이용했어요 정말,"{'purpose': 'alone', 'age_group': '30'}",alone,30,N,자연,혼자,Ex,2
317,59560,Myanmar,Yangon,5.0,3,1,가이드 투어,양곤 : 어촌마을 달라(Dala)로의 반나절 관광 투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처를 지참하셔...",편하게 잘 이용했어요 정말,"{'purpose': 'alone', 'age_group': '30'}",alone,30,N,자연,혼자,Ex,2
318,59560,Myanmar,Yangon,5.0,3,1,가이드 투어,양곤 : 어촌마을 달라(Dala)로의 반나절 관광 투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처를 지참하셔...",편하게 잘 이용했어요 정말,"{'purpose': 'alone', 'age_group': '30'}",alone,30,N,자연,혼자,Ex,2
319,39490,Myanmar,Mandalay,5.0,1,1,가이드 투어,만달레이 & 아마라푸라 : 프라이빗 자전거 투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처 출력본 혹은...",good,"{'purpose': 'children', 'age_group': '40'}",children,40,N,도시,가족,Ex,2
320,39490,Myanmar,Mandalay,5.0,1,1,가이드 투어,만달레이 & 아마라푸라 : 프라이빗 자전거 투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처 출력본 혹은...",good,"{'purpose': 'children', 'age_group': '40'}",children,40,N,도시,가족,Ex,2
321,39490,Myanmar,Mandalay,5.0,1,1,가이드 투어,만달레이 & 아마라푸라 : 프라이빗 자전거 투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처 출력본 혹은...",good,"{'purpose': 'children', 'age_group': '40'}",children,40,N,도시,가족,Ex,2
322,39485,Myanmar,Mandalay,4.0,1,1,가이드 투어,만달레이 출발 : 모니와 프라이빗 일일 투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처 출력본 혹은...",개인적으로 당일코스로는 많이 힘든곳이라투어로 다녀오시면 더 많은곳을 구석구석 구경 ...,"{'purpose': 'partner', 'age_group': '50'}",partner,50,N,자연,허니문,Kn,2
323,39485,Myanmar,Mandalay,4.0,1,1,가이드 투어,만달레이 출발 : 모니와 프라이빗 일일 투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처 출력본 혹은...",개인적으로 당일코스로는 많이 힘든곳이라투어로 다녀오시면 더 많은곳을 구석구석 구경 ...,"{'purpose': 'partner', 'age_group': '50'}",partner,50,N,도시,가족,Kn,2
324,39485,Myanmar,Mandalay,4.0,1,1,가이드 투어,만달레이 출발 : 모니와 프라이빗 일일 투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처 출력본 혹은...",개인적으로 당일코스로는 많이 힘든곳이라투어로 다녀오시면 더 많은곳을 구석구석 구경 ...,"{'purpose': 'partner', 'age_group': '50'}",partner,50,N,도시,가족,Kn,2
325,38924,Myanmar,Yangon,5.0,4,1,가이드 투어,양곤 근교 : 바고 프라이빗 일일 투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처를 지참하셔야...",양곤 여행시 꼭 가볼만한 코스이고가이드 또한 좋았습니다~,"{'purpose': 'partner', 'age_group': '50'}",partner,50,N,도시,허니문,Kn,2
326,38924,Myanmar,Yangon,5.0,4,1,가이드 투어,양곤 근교 : 바고 프라이빗 일일 투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처를 지참하셔야...",양곤 여행시 꼭 가볼만한 코스이고가이드 또한 좋았습니다~,"{'purpose': 'partner', 'age_group': '50'}",partner,50,N,도시,가족,Kn,2
327,38924,Myanmar,Yangon,5.0,4,1,가이드 투어,양곤 근교 : 바고 프라이빗 일일 투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처를 지참하셔야...",양곤 여행시 꼭 가볼만한 코스이고가이드 또한 좋았습니다~,"{'purpose': 'partner', 'age_group': '50'}",partner,50,N,도시,가족,Kn,2
328,20794,Myanmar,Yangon,4.0,1,1,가이드 투어,양곤에서 떠나는 바고(Bago) 문화 개별투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처를 지참하셔...",미얀마 시골을 볼수있는 좋은 찬스,"{'purpose': 'friends', 'age_group': '40'}",friends,40,N,자연,친구,Kn,2
329,20794,Myanmar,Yangon,4.0,1,1,가이드 투어,양곤에서 떠나는 바고(Bago) 문화 개별투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처를 지참하셔...",미얀마 시골을 볼수있는 좋은 찬스,"{'purpose': 'friends', 'age_group': '40'}",friends,40,N,도시,친구,Kn,2
330,20794,Myanmar,Yangon,4.0,1,1,가이드 투어,양곤에서 떠나는 바고(Bago) 문화 개별투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처를 지참하셔...",미얀마 시골을 볼수있는 좋은 찬스,"{'purpose': 'friends', 'age_group': '40'}",friends,40,N,도시,친구,Kn,2

In [3]:
activity['label'] = 2

In [4]:
df_activity = activity[['label', 'code', 'title', 'intro', 'review', 'area', 'company', 'interest']]

In [5]:
df_activity['corpus'] = df_activity['intro'] + df_activity['review']

C:\Users\shine\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [6]:
df_activity = df_activity[['label', 'code', 'title', 'corpus', 'area', 'company', 'interest']]

### 데이터 로드 -  book

In [7]:
keyword_book = pd.read_csv("../DATA/total_keyword_book.csv", index_col=0)
keyword_book2 = keyword_book[['ISBN', 'new_keyword', 'new_subject']]

In [8]:
book = pd.read_csv("../DATA/book_01_03_15_05_update.csv", index_col=0).reset_index(drop=True)
book

,ISBN,title,corpus,area,company,interest,comment
0,9.788957e+12,종의 기원,펴내는 작품마다 압도적인 서사와 폭발적인 이야기의 힘으로 많은 독자들의 뜨거운 사랑...,자연,혼자,Kn,NaN
1,9.788936e+12,"알로하, 나의 엄마들",따스한 손길로 마음을 어루만지는 이 시대 선한 이야기꾼 이금이 작가의 장편소설 『알...,자연,가족,Kn,NaN
2,9.788937e+12,싯다르타,"'수레바퀴 아래서', '데미안' 등으로 우리에게 친숙한 헤르만 헤세의 소설. 유복한...",자연,가족,Ar,NaN
3,9.788937e+12,노인과 바다,미국 현대 문학의 개척자라 불리는 어니스트 헤밍웨이의 대표작 『노인과 바다』. 퓰리...,자연,친구,Ar,NaN
4,9.788987e+12,왜 나는 너를 사랑하는가,인류의 역사와 함께 하는 사랑의 딜레마를 현대적인 방법으로 풀어낸 책. 작가는 1인...,자연,친구,Ex,NaN
...,...,...,...,...,...,...,...
412,9.788935e+12,팩트풀니스,"전 세계적으로 확증편향이 기승을 부리는 탈진실의 시대에, 막연한 두려움과 편견을 이...",도시,혼자,Ex,NaN
413,9.791190e+12,지적 대화를 위한 넓고 얕은 지식: 제로 편,"인문 분야 국내 작가로는 드물게 200만 부라는 더블 밀리언셀러를 기록한 작가, 출...",도시,혼자,Kn,NaN
414,9.791131e+12,내가 원하는 것을 나도 모를 때,왠지 자꾸만 마음이 쓸쓸하고 허무할 때가 있다. 지금 제대로 살고 있는 건지 앞으로...,도시,혼자,Ex,NaN
415,9.788935e+12,사피엔스,"지금으로부터 10만 년 전, 지구에는 호모 사피엔스뿐만 아니라 네안데르탈인, 호모 ...",도시,혼자,Kn,NaN
416,9.788966e+12,당신이 옳다(교보문고 단독 리커버)(찰스 장 아트 에디션),"30여 년간 정신과 의사로 활동하며 1만2천여 명의 속마음을 듣고 나누었고, 《당신...",도시,혼자,Sh,NaN

In [9]:
df_book = pd.merge(book,keyword_book2, on='ISBN', how='inner')

In [10]:
df_book['code'] = df_book['ISBN']
df_book['label'] = 1

In [11]:
df_book

,ISBN,title,corpus,area,company,interest,comment,new_keyword,new_subject,code,label
0,9.788957e+12,종의 기원,펴내는 작품마다 압도적인 서사와 폭발적인 이야기의 힘으로 많은 독자들의 뜨거운 사랑...,자연,혼자,Kn,NaN,인간본성 어머니 작가 한국소설 본성 유진,살인자 인간본성 악인,9.788957e+12,1
1,9.788936e+12,"알로하, 나의 엄마들",따스한 손길로 마음을 어루만지는 이 시대 선한 이야기꾼 이금이 작가의 장편소설 『알...,자연,가족,Kn,NaN,가족 여성 청소년소설 한국소설 장편소설 여성서사,한국소설 청소년소설 여성서사 일제강점기 근현대사 가족 여성 엄마,9.788936e+12,1
2,9.788937e+12,싯다르타,"'수레바퀴 아래서', '데미안' 등으로 우리에게 친숙한 헤르만 헤세의 소설. 유복한...",자연,가족,Ar,NaN,성장소설 데미안 사문 바라문 뱃사공 타마,성장소설,9.788937e+12,1
3,9.788937e+12,노인과 바다,미국 현대 문학의 개척자라 불리는 어니스트 헤밍웨이의 대표작 『노인과 바다』. 퓰리...,자연,친구,Ar,NaN,미국소설 노벨문학상 퓰리처상 실존철학 마지막소설 미국현대문학,퓰리처상 미국현대문학 미국소설 노벨문학상,9.788937e+12,1
4,9.788987e+12,왜 나는 너를 사랑하는가,인류의 역사와 함께 하는 사랑의 딜레마를 현대적인 방법으로 풀어낸 책. 작가는 1인...,자연,친구,Ex,NaN,사랑 연애 러브스토리 낭만 연인 실연,사랑 연애,9.788987e+12,1
...,...,...,...,...,...,...,...,...,...,...,...
412,9.788935e+12,팩트풀니스,"전 세계적으로 확증편향이 기승을 부리는 탈진실의 시대에, 막연한 두려움과 편견을 이...",도시,혼자,Ex,NaN,편견 데이터 통계 언론 침팬지 자연재해,사실충실성 탈진실 편견,9.788935e+12,1
413,9.791190e+12,지적 대화를 위한 넓고 얕은 지식: 제로 편,"인문 분야 국내 작가로는 드물게 200만 부라는 더블 밀리언셀러를 기록한 작가, 출...",도시,혼자,Kn,NaN,밀리언셀러 인문교양 우파니샤드 인문사회 제로 파편,인문사회 인문교양 지대넓얕,9.791190e+12,1
414,9.791131e+12,내가 원하는 것을 나도 모를 때,왠지 자꾸만 마음이 쓸쓸하고 허무할 때가 있다. 지금 제대로 살고 있는 건지 앞으로...,도시,혼자,Ex,NaN,문장 위로 소녀시대 태연 무기력 공감,좋은글귀 공감 위로,9.791131e+12,1
415,9.788935e+12,사피엔스,"지금으로부터 10만 년 전, 지구에는 호모 사피엔스뿐만 아니라 네안데르탈인, 호모 ...",도시,혼자,Kn,NaN,호모사피엔스 인류학 과학혁명 인류문명 네안데르탈인 지적설계,인류학 인류문명 인지혁명 농업혁명 과학혁명,9.788935e+12,1
416,9.788966e+12,당신이 옳다(교보문고 단독 리커버)(찰스 장 아트 에디션),"30여 년간 정신과 의사로 활동하며 1만2천여 명의 속마음을 듣고 나누었고, 《당신...",도시,혼자,Sh,NaN,치유 공감 심리치유 심리 피해자 기근,심리치유 심리적CPR 행동지침 공감,9.788966e+12,1

In [12]:
df_book2 = df_book[['label', 'code', 'title','corpus', 'area', 'company', 'interest']]

### 데이터 합치기

In [193]:
df_concated = pd.concat([df_activity, df_book2]).reset_index(drop=True)
df_concated

,label,code,title,corpus,area,company,interest
0,2,2.122000e+03,국립박물관과 고흐 미술관 대표작 설명,국립박물관은 렘브란트(Rermbrandt)의 대표작 '야경꾼'을 전시하기 위한 목적...,도시,혼자,Ar
1,2,1.474000e+03,암스테르담 시내 워킹투어,암스테르담은 네덜란드의 수도로서 운치와 분위기가 있는 도시입니다.그럼에도 불구하고 ...,도시,혼자,Ex
2,2,3.470000e+04,네덜란드 암스테르담 시내 실속 워킹투어,암스테르담을 실속있게 둘러볼 수 있는 투어입니다. 레이오버로 암스테르담에 잠깐 들...,도시,허니문,Ar
3,2,4.600000e+02,"히트호른, 폴른담, 풍차마을",작은 베네치아라는 별명을 가진 히트호른 마을과 네덜란드에서 가장 아름다운 전통의상을...,자연,친구,Ex
4,2,8.693000e+03,"[1+1이벤트/가격할인]프라하근교차량투어""독일 드레스덴&작센의스위스""(#할인쿠폰제공#)",*안녕하세요 하이프라하입니다! 이벤트 공지사항 1+1이벤트 공지입니다.독일 드...,자연,혼자,Ex
...,...,...,...,...,...,...,...
775,1,9.788935e+12,팩트풀니스,"전 세계적으로 확증편향이 기승을 부리는 탈진실의 시대에, 막연한 두려움과 편견을 이...",도시,혼자,Ex
776,1,9.791190e+12,지적 대화를 위한 넓고 얕은 지식: 제로 편,"인문 분야 국내 작가로는 드물게 200만 부라는 더블 밀리언셀러를 기록한 작가, 출...",도시,혼자,Kn
777,1,9.791131e+12,내가 원하는 것을 나도 모를 때,왠지 자꾸만 마음이 쓸쓸하고 허무할 때가 있다. 지금 제대로 살고 있는 건지 앞으로...,도시,혼자,Ex
778,1,9.788935e+12,사피엔스,"지금으로부터 10만 년 전, 지구에는 호모 사피엔스뿐만 아니라 네안데르탈인, 호모 ...",도시,혼자,Kn
779,1,9.788966e+12,당신이 옳다(교보문고 단독 리커버)(찰스 장 아트 에디션),"30여 년간 정신과 의사로 활동하며 1만2천여 명의 속마음을 듣고 나누었고, 《당신...",도시,혼자,Sh

In [194]:
df_concated['code'][0]

2122.0

In [195]:
# ISBN 컬럼 정리
codes = []
for i in range(len(df_concated)):
    code = str(int(df_concated['code'][i]))
    codes.append(code)
len(codes)

780

In [196]:
df_concated['code'] = codes

In [197]:
df_concated

,label,code,title,corpus,area,company,interest
0,2,2122,국립박물관과 고흐 미술관 대표작 설명,국립박물관은 렘브란트(Rermbrandt)의 대표작 '야경꾼'을 전시하기 위한 목적...,도시,혼자,Ar
1,2,1474,암스테르담 시내 워킹투어,암스테르담은 네덜란드의 수도로서 운치와 분위기가 있는 도시입니다.그럼에도 불구하고 ...,도시,혼자,Ex
2,2,34700,네덜란드 암스테르담 시내 실속 워킹투어,암스테르담을 실속있게 둘러볼 수 있는 투어입니다. 레이오버로 암스테르담에 잠깐 들...,도시,허니문,Ar
3,2,460,"히트호른, 폴른담, 풍차마을",작은 베네치아라는 별명을 가진 히트호른 마을과 네덜란드에서 가장 아름다운 전통의상을...,자연,친구,Ex
4,2,8693,"[1+1이벤트/가격할인]프라하근교차량투어""독일 드레스덴&작센의스위스""(#할인쿠폰제공#)",*안녕하세요 하이프라하입니다! 이벤트 공지사항 1+1이벤트 공지입니다.독일 드...,자연,혼자,Ex
...,...,...,...,...,...,...,...
775,1,9788934985068,팩트풀니스,"전 세계적으로 확증편향이 기승을 부리는 탈진실의 시대에, 막연한 두려움과 편견을 이...",도시,혼자,Ex
776,1,9791190313131,지적 대화를 위한 넓고 얕은 지식: 제로 편,"인문 분야 국내 작가로는 드물게 200만 부라는 더블 밀리언셀러를 기록한 작가, 출...",도시,혼자,Kn
777,1,9791130627878,내가 원하는 것을 나도 모를 때,왠지 자꾸만 마음이 쓸쓸하고 허무할 때가 있다. 지금 제대로 살고 있는 건지 앞으로...,도시,혼자,Ex
778,1,9788934972464,사피엔스,"지금으로부터 10만 년 전, 지구에는 호모 사피엔스뿐만 아니라 네안데르탈인, 호모 ...",도시,혼자,Kn
779,1,9788965746669,당신이 옳다(교보문고 단독 리커버)(찰스 장 아트 에디션),"30여 년간 정신과 의사로 활동하며 1만2천여 명의 속마음을 듣고 나누었고, 《당신...",도시,혼자,Sh

### 벡터라이즈

In [198]:
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt
%matplotlib inline

from PIL import Image
import nltk
from konlpy.corpus import kobill

In [199]:
#from konlpy.tag import Okt;
#t = Okt()
#tokens_ko = t.nouns(novel)
#tokens_ko

In [200]:
#stop_words = ['책', '.', '(', ')', ',', "'", '%', '-', 'X', ').', 'x', '의', '자', '에', '안', '변', '호', '을', '이', '다', '만', '로', '가', '를', '것', '그', '이', '관', '수', '간', '앞', '때', '내', '준', '해', '주']

In [201]:
# corpus 컬럼에 라벨링한 데이터만 추가(area, company, interest)

df_concated['corpus'] = df_concated['area'] + " "  + df_concated['company'] + " " + df_concated['interest']

In [202]:
df_concated2 = df_concated.dropna()

In [203]:
df_concated2

,label,code,title,corpus,area,company,interest
0,2,2122,국립박물관과 고흐 미술관 대표작 설명,도시 혼자 Ar,도시,혼자,Ar
1,2,1474,암스테르담 시내 워킹투어,도시 혼자 Ex,도시,혼자,Ex
2,2,34700,네덜란드 암스테르담 시내 실속 워킹투어,도시 허니문 Ar,도시,허니문,Ar
3,2,460,"히트호른, 폴른담, 풍차마을",자연 친구 Ex,자연,친구,Ex
4,2,8693,"[1+1이벤트/가격할인]프라하근교차량투어""독일 드레스덴&작센의스위스""(#할인쿠폰제공#)",자연 혼자 Ex,자연,혼자,Ex
...,...,...,...,...,...,...,...
775,1,9788934985068,팩트풀니스,도시 혼자 Ex,도시,혼자,Ex
776,1,9791190313131,지적 대화를 위한 넓고 얕은 지식: 제로 편,도시 혼자 Kn,도시,혼자,Kn
777,1,9791130627878,내가 원하는 것을 나도 모를 때,도시 혼자 Ex,도시,혼자,Ex
778,1,9788934972464,사피엔스,도시 혼자 Kn,도시,혼자,Kn
779,1,9788965746669,당신이 옳다(교보문고 단독 리커버)(찰스 장 아트 에디션),도시 혼자 Sh,도시,혼자,Sh

In [204]:
df_concated3 = df_concated2.reset_index(drop=True)

In [205]:
df_concated3 = df_concated3.dropna()

In [206]:
df_concated3

,label,code,title,corpus,area,company,interest
0,2,2122,국립박물관과 고흐 미술관 대표작 설명,도시 혼자 Ar,도시,혼자,Ar
1,2,1474,암스테르담 시내 워킹투어,도시 혼자 Ex,도시,혼자,Ex
2,2,34700,네덜란드 암스테르담 시내 실속 워킹투어,도시 허니문 Ar,도시,허니문,Ar
3,2,460,"히트호른, 폴른담, 풍차마을",자연 친구 Ex,자연,친구,Ex
4,2,8693,"[1+1이벤트/가격할인]프라하근교차량투어""독일 드레스덴&작센의스위스""(#할인쿠폰제공#)",자연 혼자 Ex,자연,혼자,Ex
...,...,...,...,...,...,...,...
765,1,9788934985068,팩트풀니스,도시 혼자 Ex,도시,혼자,Ex
766,1,9791190313131,지적 대화를 위한 넓고 얕은 지식: 제로 편,도시 혼자 Kn,도시,혼자,Kn
767,1,9791130627878,내가 원하는 것을 나도 모를 때,도시 혼자 Ex,도시,혼자,Ex
768,1,9788934972464,사피엔스,도시 혼자 Kn,도시,혼자,Kn
769,1,9788965746669,당신이 옳다(교보문고 단독 리커버)(찰스 장 아트 에디션),도시 혼자 Sh,도시,혼자,Sh

In [26]:
# labeling한 데이터로 tfidf 수행
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(analyzer='word', ngram_range=(1,2), min_df=0 ) #,stop_words=stop_words
tfidf_matrix = tf.fit_transform(df_concated3['corpus'])
tfidf_matrix

<770x55 sparse matrix of type '<class 'numpy.float64'>'
	with 770 stored elements in Compressed Sparse Row format>

In [27]:
# 유사도 측정
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
cosine_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [224]:
# Tfidft 수행
from sklearn.feature_extraction.text import TfidfVectorizer

tf_corpus = TfidfVectorizer(analyzer='word', ngram_range=(1,2), min_df=0) #, stop_words=stop_words
tfidf_matrix_corpus = tf_corpus.fit_transform(df_concated3['corpus'])
cosine_sim_corpus = linear_kernel(tfidf_matrix_corpus, tfidf_matrix_corpus)

titles = df_concated3["code"]
indices = pd.Series(df_concated3.index, index=df_concated3['code'])

In [235]:
# 추천여행을 반환하는 함수

titles1 = df_concated3[['label','code', 'title', 'corpus']]
indices1 = pd.Series(df_concated3.index,index=df_concated3['title'])

def corpus_recommendation(title):
    idx = indices1[title]
    sim_scores = list(enumerate(cosine_sim_corpus[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[0:200]
    book_indices = [i[0] for i in sim_scores]
    
    return titles1.iloc[book_indices]

In [234]:
# Tfidft 수행
from sklearn.feature_extraction.text import TfidfVectorizer

tf_corpus = TfidfVectorizer(analyzer='word', ngram_range=(1,2), min_df=0) #, stop_words=stop_words
tfidf_matrix_corpus = tf_corpus.fit_transform(df_concated3['corpus'])
cosine_sim_corpus = linear_kernel(tfidf_matrix_corpus, tfidf_matrix_corpus)

titles = df_concated3["code"]
indices = pd.Series(df_concated3.index, index=df_concated3['code'])

In [228]:
# Countervect 수행
from sklearn.feature_extraction.text import CountVectorizer

tf_corpus = CountVectorizer(analyzer='word', ngram_range=(1,2), min_df=0) #, stop_words=stop_words
tfidf_matrix_corpus = tf_corpus.fit_transform(df_concated3['corpus'])
cosine_sim_corpus = linear_kernel(tfidf_matrix_corpus, tfidf_matrix_corpus)

titles = df_concated3["code"]
indices = pd.Series(df_concated3.index, index=df_concated3['code'])

In [157]:
cosine_sim_corpus.shape

(770, 770)

#### 테스트 1 : <백범일지>(일제강점기 독립운동 역사 이야기)

In [169]:
df_book2[df_book2['title'] == "백범일지"].loc[156]['code']

9788971992258.0

In [170]:
result = corpus_recommendation("백범일지")

In [172]:
result[result['label'] == 2][0:6]

     label   code                                             title    corpus
5        2  12350                [투어] 하루에 다 보는 베를린 가이드 투어  (독일/베를린)  도시 혼자 Kn
50       2  32691  보따리투어 :: 낮보다 밤이 아름다운 피렌체 야경과 함께하는 시티투어, 피렌체 야경투어  도시 혼자 Kn
65       2  45020          [투어] 한국인 투어 코디와 함께하는 발레타 워킹 투어 :: 몰타/발레타  도시 혼자 Kn
77       2  27915          [디테일 가우디+고딕지구무료야경] 최고의 스토리텔링+구엘공원무료/동반입장  도시 혼자 Kn
110      2  14231                                   리가 음식, 문화 워킹 투어  도시 혼자 Kn
133      2  29266      아픈 현대사 속에서 도약하는 나라 세르비아,  수도 베오그라드 시내 워킹 투어!  도시 혼자 Kn

In [105]:
activity[activity['code'] == 29266].loc[141]['intro']

'발칸 지역의 중심인 세르비아는 지리적으로 유럽과 아시아, 역사적으로 서 로마와 동 로마, 종교적으로 기독교와 이슬람이 교차하는 지역에 위치에 있습니다. 이를 통해 세르비아 역사의 굴곡을 짐작해 볼 수 있습니다.  세르비아는 20세기만 8번의 전쟁을 겪을 정도로 상처와 아픔이 많은 나라입니다. 기네스북에 오른 세계 최고액의 지폐. 5천억짜리 세르비아 지폐(1993년까지 사용함)는 빵 한 봉지, 우유 한 병을 살 수 있을 정도의 가치였으니, 세르비아가 겪은 살인적인 인플레이션을 말해줍니다. 발칸의 맹주국 이었던 세르비아는 1999년 나토공습과 이후 10년 간의 경제 제제로 인해 1990년대와 2000년 대를 "잃어버린 20년"으로 불리고 있습니다. 1980년 대 공산권이 붕괴할 때만 해도 세르비아는 이웃 헝가리보다 경제가 앞섰습니다. 세르비아는 혹독한 대가를 치르고 현재 새롭게 도약하기 위해 기지개를 펴고 있습니다. 2016년 World Bank의 전 세계 기업환경 분석에서도 가장 빠르게 기업환경을 개선한 10대 국가 중 하나로 선정되었으며 2017년에도 꾸준히 개선하여 전 세계 기업 환경 47위를 기록하고 있습니다. 또한 최근, 영국의 저명한 경제 일간지인 Financial Times가 조사한 94개국 중에서 세르비아가 그린필드 투자 1위로 선정되기도 하였습니다. 세르비아의 수도 베오그라드는 약 200만 명이 살고 있는 유럽의 큰 도시 중 하나 입니다. 흰색 도시라는 의미를 가지고 있는 베오그라드는 다뉴브강과 사바강이 만나는 넓은 평원에 자리 잡고 있습니다. 베오그라드는 지난 200년 동안 40번이나 파괴되고 다시 건설된 비운의 역사, 분쟁의 아픈 역사를 만날 수 있습니다. 동시에 최근 해외 투자로 사바강 주변에 현대식 고층 건물들이 들어서고 있으며 고속버스터미널과 기차터미널 이전을 계획하고 있으며 경제성장에 박차를 가하고 있습니다.베오그라드의 웅장함에 과거 잘 살았던 세르비아 흔적을 발견할 수 있으며, 앞으로의  가능성과 미래를 볼 수 있습니다.'

#### 테스트 2 : 유명한 고전 소설, <이상한 나라의 앨리스>

In [173]:
df_book[df_book['title'] == "이상한 나라의 앨리스"].loc[53]['corpus']

'오랜 세월을 건너며 사람들의 삶 가운데 깊이 자리한 아름다운 고전들. 시대를 초월하여 사랑받아온 명작과 오늘을 대표하는 젊은 아티스트들의 감각이 하나로 만난 새로운 클래식 시리즈, 아트앤클래식Art & Classic의 첫 책이 출간되었다. 고전을 색다르게 만날 수 있도록 안내할 아트앤클래식은 1년여의 기획 기간을 거쳐 고전 작품을 선별하고, 그에 어울리는 일러스트레이터들과의 협업으로 완성되었다. 첫 책은 세계가 사랑한 일러스트레이터 퍼엉이 재해석한 『이상한 나라의 앨리스』이다. 일상 속 따뜻한 정서를 공감 가득한 그림으로 담아내온 퍼엉 작가는 자신만의 감성으로 이 책을 읽어내어 유쾌하고, 신비하고, 매력적인 캐릭터들을 탄생시켰다. 덕분에 우리는 그림을 넘겨보는 것만으로 앨리스가 이상한 나라에 빠져들었던 것처럼 이상한 나라로의 여행을 시작할 수 있게 된다.세계적인 동화작가인 루이스 캐럴의 본명은 찰스 루트위지 도지슨이다.1832년 영국 체셔 지방의 성직자 집안에서 태어난 그는 옥스퍼드 대학 수학과를 졸업하고, 모교의 교수로 재임했다. 이 책 『이상한 나라의 앨리스』는 앨리스 리델 자매들에게 들려준 이야기를 동화로 적은 것으로 1865년 정식 출간되었다. 출간된 이래 긴 시간 동안 많은 이들에게 사랑받았으며, 전 세계 수많은 나라에서 연극, 영화, 애니메이션 등으로 각색되며 판타지의 고전으로 자리매김하였다. 지은 책으로『이상한 나라의 앨리스』의 속편격인 환상동화 『거울나라의 앨리스』, 장편소설 『실비와 브루노』가 있고 시집 등을 펴냈다.대학에서 영어학을 전공하고 대학원에서 영어 교육학을 전공했다. 글밥 아카데미를 수료하고 번역가의 길로 들어섰다. 현재 캐나다 밴쿠버에서 영어를 가르치며 번역 작업을 병행하고 있다. 지은 책으로 『유학영어 길라잡이』(공저)가 있다.한국예술종합학교에서 애니메이션 예술전문사 학위를 받았다. 네이버 그라폴리오에 ‘편안하고 사랑스럽고 그래’라는 제목의 따뜻하고 공감 가득한 이야기를 연재하면서 많은 이들에게 주목받았다. 이후 세계적인 사랑을 얻으며 7개국에서 8권의 일러스트북을 출간하였다. ‘편안하고 사랑스럽고 그래’의 연재를 지속하고 있으며, 유튜브에 애니메이션 시리즈를 발표하고 있다. 이 책에서는 퍼엉만의 감성으로 『이상한 나라의 앨리스』를 재해석하여 유쾌하고, 사랑스럽고, 신비로운 캐릭터를 만들어냈다.01  토끼굴 속으로 02  눈물 웅덩이 03  코커스 달리기와 긴 이야기04  토끼가 작은 빌을 들여보내다05  애벌레의 조언06  돼지와 후추 07  엉망진창 티파티 08  여왕의 크로케 경기장09  가짜 거북의 이야기 10  바닷가재의 카드리유11  누가 타르트를 훔쳤나12  앨리스의 증언 종이책 볼 시간 많이 없는데 한번은 정독 해보고 싶은 원작이었습니다. 그림이 정말 이쁘여 아이들이 조금 더 크면 아이들도 보겠어요 종이책 볼 시간 많이 없는데 한번은 정독 해보고 싶은 원작이었습니다. 그림이 정말 이쁘여 아이들이 조금 더 크면 아이들도 보겠어요'

In [237]:
result = corpus_recommendation("이상한 나라의 앨리스")

In [238]:
### tfidfvectorizer를 썼을 떄 결과
#### interest(7) > company(4) > area(2)
result[result['label'] == 2][0:20]

     label   code                                              title    corpus
60       2  30027                              환상적인 아테네 여신의 도시 야경 투어  도시 친구 Sh
195      2  24314  [인기베스트][스냅샷&인문학 야경 VIP벤츠투어][무료샌딩][사진작가]::헝가리/부...  도시 친구 Sh
196      2  24314  [인기베스트][스냅샷&인문학 야경 VIP벤츠투어][무료샌딩][사진작가]::헝가리/부...  도시 친구 Sh
27       2  26780                          더블린의 자이언트 코즈웨이 해안 주상절리 여행  자연 친구 Sh
209      2  48669                                     트롬쇠 : 북극 자연 투어  자연 친구 Sh
263      2  45935  [투어] 인증샷 종결자! 오오투어(시크릿라군+짚라인+블루1+탐논튜빙+카약) :: 라...  자연 친구 Sh
264      2  45935  [투어] 인증샷 종결자! 오오투어(시크릿라군+짚라인+블루1+탐논튜빙+카약) :: 라...  자연 친구 Sh
290      2  48955  (고객만족도1위) 원조! 푸트라자야 + 반딧불 : 입장료+간식+석식 (리얼가이드 단...  자연 친구 Sh
291      2  48955  (고객만족도1위) 원조! 푸트라자야 + 반딧불 : 입장료+간식+석식 (리얼가이드 단...  자연 친구 Sh
293      2  41521                    [투어] 무아라 반딧불 투어 :: 말레이시아/코타키나발루  자연 친구 Sh
294      2  41521                    [투어] 무아라 반딧불 투어 :: 말레이시아/코타키나발루  자연 친구 Sh
299      2  31243                             [투어] 코타키나발루 나나문 반딧불 투어  자연 친구 Sh
300      2  31243                             [투어] 코타키나발루 나나문 반딧불 투어  자연 친구 Sh
302      2  44560             [투어] 사피+마누칸 섬 플라이 호핑투어 :: 말레이시아/코타키나발루  자연 친구 Sh
303      2  44560             [투어] 사피+마누칸 섬 플라이 호핑투어 :: 말레이시아/코타키나발루  자연 친구 Sh
13       2  50896                             [니스 출발] 모나코 & 에즈 전일 투어  도시 친구 Ex
14       2  50894                    [니스 출발] 모나코 & 몬테 카를로 & 에즈 전일 투어  도시 친구 Ex
18       2   5929    벨기에 당일투어 (브뤼헤 + 브뤼셀 + 스냅사진 + 숙소샌딩 + 10가지 할인 혜택)  도시 친구 Ex
63       2  22345                            몬테네그로 일일투어 / 두브로브니크 출발   도시 친구 Ex
100      2   3608                    [투어] 하루에 다 보는 이스탄불 투어 (터키/이스탄불)  도시 친구 Ex

In [233]:
### countervetorizer를 썼을 떄 결과
#### title > company를 우선
result[result['label'] == 2][0:20]

     label   code                                              title    corpus
60       2  30027                              환상적인 아테네 여신의 도시 야경 투어  도시 친구 Sh
195      2  24314  [인기베스트][스냅샷&인문학 야경 VIP벤츠투어][무료샌딩][사진작가]::헝가리/부...  도시 친구 Sh
196      2  24314  [인기베스트][스냅샷&인문학 야경 VIP벤츠투어][무료샌딩][사진작가]::헝가리/부...  도시 친구 Sh
13       2  50896                             [니스 출발] 모나코 & 에즈 전일 투어  도시 친구 Ex
14       2  50894                    [니스 출발] 모나코 & 몬테 카를로 & 에즈 전일 투어  도시 친구 Ex
16       2  13724                칸 출발 : 모나코 & 몬테 카를로 & 에즈 빌리지 반나절 투어  도시 친구 Ar
18       2   5929    벨기에 당일투어 (브뤼헤 + 브뤼셀 + 스냅사진 + 숙소샌딩 + 10가지 할인 혜택)  도시 친구 Ex
19       2  19954                     **브뤼셀출발** 브뤼셀+브뤼헤+겐트 단독 차량투어!   도시 친구 Kn
27       2  26780                          더블린의 자이언트 코즈웨이 해안 주상절리 여행  자연 친구 Sh
28       2  46016        [투어] 더블린 현재와 과거를 함께 둘러보는 필수 시티투어 (아일랜드/더블린)  도시 친구 Fo
30       2   1829              [후기1400개] 코츠월드+옥스포드 #점심제공 #빠른입장 #옥코1위  도시 친구 Ar
33       2   1867                     [후기1000개] 대영박물관 집중투어 - 베스트 셀러   도시 친구 Ar
35       2  40905                                  런던 해리포터 스튜디오 입장권   도시 친구 Et
42       2   2007                 ★[10주년 50% 할인이벤트] 바티칸 집중콘서트(반일투어)   도시 친구 Ar
54       2  48868  휴장[e-바우처/모바일 제시가능] 파리 디즈니랜드 입장권 e-티켓 1 DAY 2 PARK  도시 친구 Et
59       2  30028                          유일한 고대 아테네 문화산책 투어,  페리파토  도시 친구 Ar
63       2  22345                            몬테네그로 일일투어 / 두브로브니크 출발   도시 친구 Ex
66       2  58667      [투어]걸어서세계속으로 메인코디의 수도발레타 반일투어(입장료포함) (몰타/발레타)  도시 친구 Kn
68       2  73602     [투어]걸어서 세계 속으로 메인 코디의 고조섬 전일 투어(택시비포함) (몰타/고조)  도시 친구 Ar
70       2  62035  [투어]걸어서세계속으로 메인코디의 라밧-임디나 반일 투어(입장료 포함)(몰타/라밧/...  도시 친구 Fo

In [80]:
### <환상적인 아테네 여신의 도시 야경 투어> :  도시, 친구, Sh (여행정보)
### https://www.myrealtrip.com/offers/30027

activity[activity['code'] == 30027].loc[66]['intro']

'지중해 태양 빛이 사라짐과 동시에 고대도시 아테네는 신비한 자태를 드러내기 시작한다. 특히 한여름에는 기온이 너무 높기 때문에 지중해 지역 밤 문화를 즐기며 고대 도시를 걸어 보는 낭만을 놓쳐서는 안 된다. 석양이 지면서 차례로 켜지는 조명에 의해 드러나는 아크로폴리스 위에 있는 나이키 신전, 프로필레아, 피나코씨끼, 파르테논 신전, 에릭씨온 신전은 신비롭게 짝이 없다. 아크로폴리스와 아테네 시내가 한눈에 보이는 루프가든에서 그리스 냉커피인 프라페나 토종 미쏘스 맥주를 한잔하면 모든 피로와 더위를 한 방에 날려 버릴 수 있다.'

In [81]:
### <환상적인 아테네 여신의 도시 야경 투어> : 도시, 친구, Sh (리뷰)
activity[activity['code'] == 30027].loc[66]['review']

'비수기라 소수로 차량이용해서 다녀서 편하고 빠르게 구경할 수 있어서 좋앗습니다. 아크로폴리스 둘래길돌면서 설명도 잘 해주시고.사진찍는거 다 기다려주시고 정말 신전만 몇 개 보고 갈 줄 알았더니 여러곳 많이 가서 좋았습니다.. 아테네 여행 4일차인가에 했는데 투어했을 때가 제일 재밌었어요ㅋㅋ 추천!!!!! 차량을 이용하여 보다 수월하게 투어할 수 있었습니다 사진도 잘 찍어주시고 일정도 유동적으로 친절히 잘 조절해 주셨어요 ^^'

#### 테스트 3 : 오늘 밤은 굶고 자야지 (도시에서 다이어터로 사는 이야기)

In [230]:
result = corpus_recommendation("오늘 밤은 굶고 자야지")

In [227]:
### tfidf vectorizer 를 써서 예측했을 때 결과
#### interest를 우선
result[result['label'] == 2][0:10]

     label   code                                              title    corpus
20       2   3554              브뤼셀 워킹투어 (시티투어+와플가게+현지맛집 추천+벨기에맥주 소개)  도시 혼자 Fo
22       2   5097                            **브뤼셀** 벨기에 맥주 테이스팅 투어   도시 혼자 Fo
104      2  45262                              리스본 미식워킹투어 (포르투갈/리스본)  도시 혼자 Fo
127      2  14458                    빌니우스 : 여행하는 미식가들을 위한 3시간 미식 탐험!  도시 혼자 Fo
147      2  52198                      [투어] 키예프 테이스티 투어 :: 우크라이나/키예프  도시 혼자 Fo
28       2  46016        [투어] 더블린 현재와 과거를 함께 둘러보는 필수 시티투어 (아일랜드/더블린)  도시 친구 Fo
70       2  62035  [투어]걸어서세계속으로 메인코디의 라밧-임디나 반일 투어(입장료 포함)(몰타/라밧/...  도시 친구 Fo
101      2  62526      [세나투어] 미식&워킹투어:보스포러스선셋/야경+아시아지구 로컬체험(터키/이스탄불)  도시 친구 Fo
343      2  21301                                씨엠립 : 캄보디아 마을 요리 교실  도시 친구 Fo
344      2  21301                                씨엠립 : 캄보디아 마을 요리 교실  도시 친구 Fo

In [231]:
### countervectorizer 를 써서 예측했을 때 결과
#### company를 우선
result[result['label'] == 2][0:10]

     label   code                                  title    corpus
20       2   3554  브뤼셀 워킹투어 (시티투어+와플가게+현지맛집 추천+벨기에맥주 소개)  도시 혼자 Fo
22       2   5097                **브뤼셀** 벨기에 맥주 테이스팅 투어   도시 혼자 Fo
104      2  45262                  리스본 미식워킹투어 (포르투갈/리스본)  도시 혼자 Fo
127      2  14458        빌니우스 : 여행하는 미식가들을 위한 3시간 미식 탐험!  도시 혼자 Fo
147      2  52198          [투어] 키예프 테이스티 투어 :: 우크라이나/키예프  도시 혼자 Fo
0        2   2122                  국립박물관과 고흐 미술관  대표작 설명  도시 혼자 Ar
1        2   1474                          암스테르담 시내 워킹투어  도시 혼자 Ex
5        2  12350     [투어] 하루에 다 보는 베를린 가이드 투어  (독일/베를린)  도시 혼자 Kn
12       2  50891             [니스 출발] 리베이라 최고를 찾아 떠나는 여행  도시 혼자 Ex
15       2  38847           니스에서 출발하는 에즈/모나코/몬테카를로 반일 투어  도시 혼자 Ex

#### 테스트 4 : 신경 끄기의 기술

In [147]:
result = corpus_recommendation("신경 끄기의 기술")

In [148]:
result[result['label'] == 2][0:6]

    label   code                                           title    corpus
1       2   1474                                   암스테르담 시내 워킹투어  도시 혼자 Ex
12      2  50891                      [니스 출발] 리베이라 최고를 찾아 떠나는 여행  도시 혼자 Ex
15      2  38847                    니스에서 출발하는 에즈/모나코/몬테카를로 반일 투어  도시 혼자 Ex
36      2  27564  [세븐시스터즈+브라이튼]#런던1위#재미와 감동이 있는 소풍투어# 시즌특가 7만9천원  도시 혼자 Ex
58      2  37376                          [당일발행] 파리 바토 파리지앵 E-티켓  도시 혼자 Ex
67      2  34416                  몰타의 자매섬인 '고조섬(gozo)'에서의 원데이 투어  도시 혼자 Ex